// <auto-generated />
using System;
using CSM.TabulationSystem.Web.Infrastructure.Data.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSM.TabulationSystem.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20181010155402_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.Contestant", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid?>("EventId");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.Criterion", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid?>("EventId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Percentage");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.Event", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Description");

                    b.Property<bool>("IsLocked");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.EventResult", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContestantId");

                    b.Property<Guid?>("EventId");

                    b.Property<string>("Ordinal");

                    b.Property<decimal>("Points");

                    b.Property<int>("Rank");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("EventResults");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.Judge", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EventId");

                    b.Property<string>("EventKey");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Totem");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.Score", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContestantId");

                    b.Property<Guid?>("CriterionId");

                    b.Property<Guid?>("EventId");

                    b.Property<Guid?>("JudgeId");

                    b.Property<decimal>("Points");

                    b.Property<DateTime>("Timestamp");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("CSM.TabulationSystem.Web.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("LoginStatus");

                    b.Property<int>("LoginTrials");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("RegistrationCode");

                    b.Property<int>("Role");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
